version: "3.9"

services:
  squid-panel:
    build: .
    container_name: squid-panel
    privileged: true
    ports:
      - "8444:8444"
    environment:
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASS=${ADMIN_PASS:-password}
      - SESSION_SECRET=${SESSION_SECRET:-ALFA_PRO_KEY_99}
    volumes:
      - ./:/app:rw
      - /etc/squid-panel:/etc/squid-panel:rw
      - /etc/sysconfig/network-scripts:/etc/sysconfig/network-scripts:rw
      - /var/backups/squid-panel:/var/backups/squid-panel:rw
      - /etc/squid:/etc/squid:rw
    restart: unless-stopped
